[marron] 기본 화면 구현
codesquad-members-2024/fe-data-fetching pull request #1
Opened 2024-04-08 08:57 UTC by dmdeh

## 구현 내용
typescript, express 설치 및 기본 화면 구현

## 고민 사항
script 연결, express 사용 방식 고민 중...

## 기타
typescript 사용은 express로 적당히 구현 후 진행해보기...

2024-04-11 05:52 UTC, crongro commented
> 으로 선택된 뉴스콘텐츠는 추가적인 API요청을 통해서 받기
> -> 추가적인 요청이 어떤식으로 해야하는지.. 지금 하는 방향이 맞는지.........

아 선택된 뉴스의 데이터를 그때(자동선택된 시점) 가져오면 됩니다.

2024-04-11 06:00 UTC, crongro requested changes
구현사항을 수정하시고 다시 push 해주세요~

2024-04-11 06:00 UTC, crongro commented on app.js
> +var app = express();
기본코드지만 express 코드 역시 과거 문법을 쓸 이유는 없죠.
const, let 을 사용~

2024-04-11 06:00 UTC, crongro commented on public/js/news.js
> +    .then((data) => {
이제 가급적 async 함수를 사용해보세요.

2024-04-11 06:00 UTC, crongro commented on public/js/news.js
> +  let click;
부적절한 변수명

2024-04-11 06:00 UTC, crongro commented on public/js/news.js
> +    if (event.target.tagName === "P") {
해체할당에 이제는 익숙해져야할 때..

2024-04-11 06:00 UTC, crongro commented on public/js/news.js
> +      }, 3000);
이전에 만드신 delay 함수를 사용하심이?

2024-04-11 06:00 UTC, crongro commented on public/js/onEvent.js
> +    location.reload();
reload가 필요한 경우가 있어요? 새로고침은 spa에서는 필요 없을것 같아요.

2024-04-14 02:08 UTC, crongro approved these changes

2024-04-14 02:08 UTC, crongro commented on public/js/components/delay.js
> +class Delay {
class에 하나의 메서드만 있죠? 객체를 생성하기보다는 간단히 함수를 사용하는것이 더 나을거 같아요.
(학습의 이유라면 좋고요)

2024-04-14 02:08 UTC, crongro commented on public/js/view/news.js
> +    shuffledData.forEach((item) => {
위에서는 하고 여기서는 왜 titlelist null체크를 안해요?

2024-04-14 02:08 UTC, crongro commented on public/js/view/news.js
> +    const firstPTag = titleList.querySelectorAll("p")[0];
0번째가 항상 원하는 태그가 맞을지 고민해야하는 코드입니다.

2024-04-14 02:08 UTC, crongro commented on public/js/view/onEvent.js
> +
hanldeupdate가 3000 이라는 변수값을 받아서 함수의 범용성을 올리세요

2024-04-14 02:09 UTC, merged

2024-04-14 05:56 UTC, dmdeh commented on public/js/view/news.js
> +    shuffledData.forEach((item) => {
갱신될 때마다 왼쪽 titleList에 += 으로 제목을 붙여주는 코드라서 위에서 내용 제거 후 innerHTML에 넣어주는 형태입니다