[George]: express 초기 세팅 및 json생성
codesquad-members-2024/fe-data-fetching pull request #4
Opened 2024-04-08 13:40 UTC by 96limshyun

## 구현 내용
 - express 설치 및 기초 학습
 - Json파일 생성 및 import로 데이터 가져오기
 - 웹 디자인 및 초기 세팅
 - 
## 고민 사항
 - 파일 구조 및 observer 패턴 적용
 - AbortController 사용
 - ts 사용

2024-04-11 06:27 UTC, crongro requested changes
참고해서 수정/개발하세요~

2024-04-11 06:27 UTC, crongro commented on public/src/controller/eventController.ts
> +    let timer: number = TIMER_INITIAL;
타입추론이 되는것을 고려해서 이정도 타입선언은 생략도 가능

2024-04-11 06:27 UTC, crongro commented on public/src/controller/eventController.ts
> +let increase = null;
이 변수는 RunTimer. 안으로는 못 옮기는거죠?

2024-04-11 06:27 UTC, crongro commented on public/src/model/newsAPI.js
> +var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
ts(원래 소스)만 소스커밋 대상으로 관리하세요~ js는 불필요.

2024-04-11 06:27 UTC, crongro commented on public/src/model/newsAPI.js
> +var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
그리고 js를 같은 디렉토리에 두기보다는.. (볼필요가 없기때문에) dist등의 디렉토리에 모아져도 좋죠.

2024-04-11 06:27 UTC, crongro commented on public/src/view/viewRenderer.ts
> +interface NewsItem {
interface 활용좋네요.

2024-04-11 07:12 UTC, limshyun commented on public/src/controller/eventController.ts
> +let increase = null;
안으로 옮기면 startTimer가 실행될때마다 Iincrease가 중복 생성돼서 타이머가 여러개 랜더링 됩니다 ㅠㅠ 방법 찾아보겠습니다!

2024-04-11 07:40 UTC, 96limshyun commented on public/src/controller/eventController.ts
> +let increase = null;
```
const showSelectNews = async(select: string) => {
    timer.stopTimer()

    try {
        newsModel.updateNewsIndex(select)
        const selectContent = await getNewsContent(select)
        renderNewsContent(selectContent)
        timer.startTimer()
    } catch(error) {
        console.log("getContent error", error)
    }
}
```
finally에서 startTimer를 실행하지 않고 getNewsContent에서 fetch로 데이터를 받았을때만 startTimer를 실행해줘서 해결했습니다!

2024-04-12 13:02 UTC, merged

2024-04-14 02:59 UTC, crongro commented on public/src/controller/eventController.ts
> +        console.log("getContent error", error)
try/catch/finally 까지 좋고요
개발자들에게 에러를 알려주는 것이라면 log보다는 error메서드를 사용

2024-04-14 02:59 UTC, crongro commented on public/src/view/viewRenderer.ts
> +    const mainNewsContainer: HTMLElement = document.querySelector(".main-news-section")
htmlelement보다 더 구체적인 html 태그 타입을 쓸 수 있는지 알아보세요